site_name: Scalar DL Docs
repo_url: https://github.com/scalar-labs/scalardl
nav:
- Home: index.md
- How to use:
    - Getting started with Sandbox: sandbox.md
    - Installation with Docker (Partner-only): installation-with-docker.md
    - Getting started: getting-started.md
    - How to write a contract: how-to-write-contract.md
    - Trouble-shooting guide: trouble-shooting-guide.md
    - Sample applications:
        - Simple banking application: applications/simple-bank-account/README.md
- Design:
    - Design document: design.md
- Operation:
    - Cluster setup guide: cluster-setup-guide.md
  #- Release notes:
  #- Overview: release_notes/index.md
  #- "Version 0.9.10": release_notes/0_9_10.md
theme: readthedocs
